apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  labels:
    app: message-service
data:
  SPRING_DATA_MONGODB_HOST: "mongo-svc"
  SERVER_USEFORWARDHEADERS: "true"

---
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-deployment
  labels:
    app: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: mrflick72/message-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: message-service-config
---

kind: Service
apiVersion: v1
metadata:
  name: message-service
spec:
  selector:
    app: message-service
  ports:
    - protocol: TCP
      port: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: message-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /message-service/?(.*)
            backend:
              serviceName: message-service
              servicePort: 8080